defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# Disable obstacle avoidance
disable_obstacle_avoidance: True

# Goal, specified relative to Spot
# goal_x: 38.0
# goal_y: -16.0
goal_x: 38.0
goal_y: -12.5

# Policy configs
weights: weights/map_policies/spot_depth_context_resnet18_map_prevact_sincos32_log_rot_100_0.5_sd_1_ckpt_67.pth
# weights: weights/map_policies/spot_depth_context_resnet18_map_prevact_sincos32_log_rot_100_0.5_sd_1_ckpt_60.pth
# weights: weights/map_policies/spot_depth_context_vit_map_prevact_sincos32_log_rot_128_0.5_LSTM2_sd_1_ckpt_84.pth
# weights: weights/map_policies/spot_depth_context_vit_map_prevact_sincos32_log_rot_128_0.5_sd_1_ckpt_97.pth
# weights: weights/map_policies/spot_depth_context_vit_map_prevact_sincos32_log_rot_128_0.5_sd_1_ckpt_99.pth
# weights: weights/map_policies/spot_depth_context_cnn2d_map_prevact_sincos32_log_rot_100_0.5_sd_1_ckpt_81.pth
# weights: weights/map_policies/spot_depth_context_cnn2d_map_prevact_sincos32_log_rot_100_0.5_sd_1_ckpt_98.pth
# weights: weights/map_policies/spot_depth_context_resnet18_map_prevact_sincos32_log_rot_100_0.5_sd_1_ckpt_94.pth
# weights: weights/map_policies/spot_depth_context_resnet18_map_prevact_sincos32_log_rot_100_0.5_sd_1_ckpt_99.pth
sensor_type: depth
policy_name: PointNavContextPolicy
use_horizontal_velocity: False
deterministic: True 

# waypoint configs
use_local_coords: True
waypoint_start: -1 
waypoint_end: -1

# Control configs
ctrl_hz: 2
max_lin_dist: 0.25 # m/s
max_ang_dist: 0.26 # rad/s

# Success criteria
success_dist: 0.35
project_goal: -1  
log_goal: True
max_episode_steps: 500

# context configs
context_type: map
# map: maps/1157_map_traj_v22.png
# map: maps/1157_map_traj_left_v2.png
# map: maps/1157_map_traj.png
map: maps/1157_map_traj_left_full.png
# map: maps/1157_map_traj_left_further.png
# map: maps/1157_map_traj_left_closer.png
# map: maps/1157_map_straight.png
# map: maps/1157_map_right.png
# map: maps/1157_map_traj_right_v2.png
map_resolution: 100
# map_resolution: 128
meters_per_pixel: 0.7

# Debug mode
debug: False # saves images to disk
timeout: -1 # terminate if X seconds passes. Set to -1 if you don't want to use a timeout
use_keyboard: False # wait for keyboard input before stepping robot

hydra:
  output_subdir: null
  run:
    dir: .