defaults:
  - _self_
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# Disable obstacle avoidance
disable_obstacle_avoidance: True

# Goal, specified relative to Spot
goal_x: 38.0
goal_y: -16.5
# goal_x: 2.0
# goal_y: 0.0

# Policy configs
## Trained given a map as input. Can get from 1157 to 1161 
#weights: weights/map_policies/spot_depth_context_resnet18_map_prevact_sincos32_log_rot_100_0.5_sd_1_ckpt_67.pth
## New policy using adaptive map scaling
# weights: weights/map_policies/spot_depth_context_resnet18_map_prevact_linear512_log_rot_100_-1.0_sd_1_ckpt_67.pth
#weights: weights/map_policies/spot_depth_context_resnet18_map_prevact_linear512_log_rot_100_-1.0_sd_1_ckpt_92.pth
# weights: weights/pointnav_policies/spot_depth_context_resnet18_map_prevact_sincos32_log_rot_100_-1.0_robot_scale_0.1_bp_0.3_sd_1_v2_ckpt_91.pth
weights: weights/map_policies/spot_depth_context_resnet18_map_prevact_sincos32_log_rot_100_-1.0_cma_sd_1_ckpt_98.pth

sensor_type: depth
policy_name: PointNavContextCMAPolicy
use_horizontal_velocity: False
deterministic: True 

# waypoint configs
use_local_coords: True
waypoint_start: -1 
waypoint_end: -1

# Control configs
ctrl_hz: 2
max_lin_dist: 0.25 # m/s
max_ang_dist: 0.26 # rad/s

# Success criteria
success_dist: 0.35
project_goal: -1  
log_goal: True
max_episode_steps: 500

# context configs
context_type: map
# map: maps/coda_map.png
# map: maps/coda_map_left.png
# map: maps/coda_map_right_v3.png
# map: maps/map_white.png
map: maps/1157_map_traj_left_further.png
map_goal: maps/1157_map_traj_left_goals.png
# map: maps/1157_map_traj_left_closer.png
#map: maps/1157_map_straight.png
# map: maps/1157_map_right.png
map_resolution: 100
# map_resolution: 128
#meters_per_pixel: 0.1
meters_per_pixel: 1.0
use_agent_map: True

# Debug mode
debug: True # saves images to disk
timeout: -1 # terminate if X seconds passes. Set to -1 if you don't want to use a timeout
use_keyboard: False # wait for keyboard input before stepping robot

hydra:
  output_subdir: null
  run:
    dir: .
