defaults:
  - _self_
  - waypoints: 1157_to_1161_gt_local.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# Disable obstacle avoidance
disable_obstacle_avoidance: True

# Goal, specified relative to Spot

# Policy configs
#weights: weights/spot_depth_simple_cnn_cutout_nhy_2hz_sd_1_ckpt_45.pth
weights: weights/spot_depth_simple_cnn_cutout_nhy_2hz_rand_pitch_sd_1_ckpt_63.pth
sensor_type: depth
policy_name: PointNavContextPolicy
context_type: waypoint
use_horizontal_velocity: False
use_local_coords: True

# Control configs
ctrl_hz: 2
max_lin_dist: 0.25 # m/s
max_ang_dist: 0.26 # rad/s

# Success criteria
success_dist: 0.28
max_episode_steps: 500

# Debug mode
debug: False # saves images to disk
timeout: -1 # terminate if X seconds passes. Set to -1 if you don't want to use a timeout
use_keyboard: False # wait for keyboard input before stepping robot

hydra:
  output_subdir: null
  run:
    dir: .