defaults:
  - _self_
  - waypoints: 1157_to_1161_waypoint.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# Disable obstacle avoidance
disable_obstacle_avoidance: True

# Goal, specified relative to Spot

# Policy configs
weights: weights/spot_depth_simple_cnn_cutout_nhy_2hz_ny_rand_pitch_-1.0_1.0_bp_0.03_sd_2_16env_context_no_noise_log_waypoint_ckpt_64.pth
sensor_type: depth
policy_name: PointNavContextPolicy
use_horizontal_velocity: False
deterministic: True 

# waypoint configs
use_local_coords: True
waypoint_start: -1 
waypoint_end: -1

# Control configs
ctrl_hz: 2
# max_lin_dist: 0.25 # m/s
# max_ang_dist: 0.26 # rad/s
max_lin_dist: 0.35 # m/s
max_ang_dist: 0.26 # rad/s

# Success criteria
success_dist: 0.32
project_goal: -1  
log_goal: True
max_episode_steps: 500

# context configs
context_type: waypoint
map_res: 256

# Debug mode
debug: False # saves images to disk
timeout: -1 # terminate if X seconds passes. Set to -1 if you don't want to use a timeout
use_keyboard: False # wait for keyboard input before stepping robot

hydra:
  output_subdir: null
  run:
    dir: .