# 0:
#   goal_x: 3.0
#   goal_y: 0.0
# 1:
#   goal_x: 3.0
#   goal_y: 0.0
# 2:
#   goal_x: 3.0
#   goal_y: 0.0
# 3:
#   goal_x: 3.0
#   goal_y: 0.0
0:
  goal_x: 1.0
  goal_y: 0.0
1:
  goal_x: 1.0
  goal_y: -1.0
2:
  goal_x: 1.0
  goal_y: 1.0
3:
  goal_x: 1.0
  goal_y: -1.0
4:
  goal_x: 1.0
  goal_y: 1.0
5:
  goal_x: -1.0
  goal_y: 0.0
6:
  goal_x: -1.0
  goal_y: -1.0
7:
  goal_x: -1.0
  goal_y: 1.0
8:
  goal_x: -1.0
  goal_y: -1.0
9:
  goal_x: -1.0
  goal_y: 1.0