  0:
    goal_x: 2.5
    goal_y: 1.8
  1:
    goal_x: 2.0066
    goal_y: 1.9558
  2:
    goal_x: 4.1402
    goal_y: 1.0922
  3:
    goal_x: 3.81
    goal_y: 0.8636
  4: # slope 
    goal_x: 5.9436
    goal_y: 0.3048
  5: 
    goal_x: 2.8448
    goal_y: 1.524
  6: # starts to turn right
    goal_x: 2.0828
    goal_y: 1.8034
  7:
    goal_x: 0.7874 
    goal_y: -3.048
  8:
    goal_x: 0.7874
    goal_y: -3.708
  9:
    goal_x: 0.0
    goal_y: -4.4704
  10:
    goal_x: 0.0
    goal_y: -3.5814
  11:
    goal_x: 0.864
    goal_y: -3.5814
  12:
    goal_x: 2.1082
    goal_y: -2.667
  13:
    goal_x: 3.8862
    goal_y: 0.0
  14:
    goal_x: 3.9624
    goal_y: 0.31496
  15:
    goal_x: 2.5146
    goal_y: 1.3716
  16: # ends by the stairs
    goal_x: 2.3368
    goal_y: 1.0922