  0:
    goal_x: 2.45
    goal_y: 2.08
  1:
    goal_x: 4.7
    goal_y: 4.28
  2:
    goal_x: 9.45
    goal_y: 7.23
  3:
    goal_x: 14.35
    goal_y: 0.0
  # 4: # slope 
  #   goal_x: 7.0
  #   goal_y: 0.0
  # 5: 
  #   goal_x: 2.2
  #   goal_y: -3.2
  # 6:
  #   goal_x: 0.91
  #   goal_y: -3.14
  # 7:
  #   goal_x: 1.03
  #   goal_y: -3.9
  # 8:
  #   goal_x: 0.0
  #   goal_y: -4.62
  # 9:
  #   goal_x: 0.0
  #   goal_y: -3.82
  # 10:
  #   goal_x: 1.15
  #   goal_y: -3.66
  # 11:
  #   goal_x: 3.05
  #   goal_y: -3.32
  # 12:
  #   goal_x: 4.04
  #   goal_y: -1.0
  # 13:
  #   goal_x: 4.11
  #   goal_y: 0.0
  # 14:
  #   goal_x: 2.82
  #   goal_y: 1.0
  # 15:
  #   goal_x: 2.44
  #   goal_y: 2.51